server:
  port: 9292
#
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: sk-group-3
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages : com.Kafka_consumer.Consumer.dto
#          deserializer:
#            key:
#              delegate:
#                class: org.apache.kafka.common.serialization.StringDeserializer
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer

#spring:
#  kafka:
#    consumer:
#      enable-auto-commit: true
#      bootstrap-servers: localhost:9092
#      group-id: sk-group-4
#      auto-offset-reset: earliest
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#
#

